# Adjust parameters to suit project, then save as 'projectName_parameters.yaml'

### GENERIC PARAMETERS ###
srb_dir: /space/wib_data/CLIMATE/NASA/srb_3hr/
itopo_dir: /home/sl_wib/ITopo/
first_year: 2006
last_year: 2006
months:  03 06 12

