### PROJECT NAME ###
example:

    ### DEFINE PATHS TO IMPORTANT DIRECTORIES ###
    src_dem: /path/to/dem.tif
    srb_dir: /path/to/srb/
    itopo_dir: /path/to/itopo_output/

    ### DEFINE SPATIAL EXTENTS ###
    # If epsg does not match src_dem, gdalwarp might reproject src_dem to produce aoi dem
    # If EPSG is not given, it is derived from src_dem.
    epsg: 32633 # EPSG code for AOI projection. if prj_dem exists, this param value will be ignored
    dx: 100  # E-W Resolution of prj_dem and output. if prj_dem exists, this param value will be ignored
    dy: -100 # (negative) N-S Resolution of prj_dem and output. if prj_dem exists, this param value will be ignored
    xmin: 0 # easting of AOI's left edge, if prj_dem exists, this param value will be ignored
    ymin: 0 # northing of AOI's bottom edge, if prj_dem exists, this param value will be ignored
    xmax: 4 # easting of AOI's right edge, if prj_dem exists, this param value will be ignored
    ymax: 4 # northing of AOI's top edge, if prj_dem exists, this param value will be ignored

    ### TEMPORAL RANGE ###
    months: 01 02 03 04 05 06 07 08 09 10 11 12
    first_year: 1984
    last_year: 2007
########################################################################################################################


### PROJECT NAME ###
gjende10m:

    ### DEFINE PATHS TO IMPORTANT DIRECTORIES ###
    src_dem: /space/dems/dted10/6804_2_10m_z32.dem
    srb_dir: /space/wib_data/CLIMATE/NASA/srb_monthly_utc/
    itopo_dir: /home/sl_wib/ITopo/gjende10m/

    ### DEFINE SPATIAL EXTENTS ###
    # If epsg does not match src_dem, gdalwarp might reproject src_dem to produce aoi dem
    # If EPSG is not given, it is derived from src_dem.
    #epsg:   32633 # EPSG code for AOI projection. if prj_dem exists, this param value will be ignored
    #dx:      1000 # E-W Resolution of prj_dem and output. if prj_dem exists, this param value will be ignored
    #dy:     -1000 # (negative) N-S Resolution of prj_dem and output. if prj_dem exists, this param value will be ignored
    #min:  -85000 # easting of AOI's left edge, if prj_dem exists, this param value will be ignored
    #ymin: 6430000 # northing of AOI's bottom edge, if prj_dem exists, this param value will be ignored
    #xmax: 1125000 # easting of AOI's right edge, if prj_dem exists, this param value will be ignored
    #ymax: 7962000 # northing of AOI's top edge, if prj_dem exists, this param value will be ignored

    ### TEMPORAL RANGE ###
    months: 01 02 03 04 05 06 07 08 09 10 11 12
    first_year: 1997
    last_year: 2002
########################################################################################################################


### PROJECT NAME ###
gjende100m:

    ### DEFINE PATHS TO IMPORTANT DIRECTORIES ###
    src_dem: /space/dems/dted10/6804_2_10m_z32.dem
    srb_dir: /space/wib_data/CLIMATE/NASA/srb_monthly_utc/
    itopo_dir: /home/sl_wib/ITopo/gjende100m/

    ### DEFINE SPATIAL EXTENTS ###
    # If epsg does not match src_dem, gdalwarp might reproject src_dem to produce aoi dem
    # If EPSG is not given, it is derived from src_dem.
    #epsg:   32633 # EPSG code for AOI projection. if prj_dem exists, this param value will be ignored
    #dx:      1000 # E-W Resolution of prj_dem and output. if prj_dem exists, this param value will be ignored
    #dy:     -1000 # (negative) N-S Resolution of prj_dem and output. if prj_dem exists, this param value will be ignored
    #min:  -85000 # easting of AOI's left edge, if prj_dem exists, this param value will be ignored
    #ymin: 6430000 # northing of AOI's bottom edge, if prj_dem exists, this param value will be ignored
    #xmax: 1125000 # easting of AOI's right edge, if prj_dem exists, this param value will be ignored
    #ymax: 7962000 # northing of AOI's top edge, if prj_dem exists, this param value will be ignored

    ### TEMPORAL RANGE ###
    months: 01 02 03 04 05 06 07 08 09 10 11 12
    first_year: 1998
    last_year: 2001
########################################################################################################################


### PROJECT NAME ###
gjende1000m:

    ### DEFINE PATHS TO IMPORTANT DIRECTORIES ###
    src_dem: /space/dems/dted10/6804_2_10m_z32.dem
    srb_dir: /space/wib_data/CLIMATE/NASA/srb_monthly_utc/
    itopo_dir: /home/sl_wib/ITopo/gjende1000m/

    ### DEFINE SPATIAL EXTENTS ###
    # If epsg does not match src_dem, gdalwarp might reproject src_dem to produce aoi dem
    # If EPSG is not given, it is derived from src_dem.
    #epsg:   32633 # EPSG code for AOI projection. if prj_dem exists, this param value will be ignored
    #dx:      1000 # E-W Resolution of prj_dem and output. if prj_dem exists, this param value will be ignored
    #dy:     -1000 # (negative) N-S Resolution of prj_dem and output. if prj_dem exists, this param value will be ignored
    #min:  -85000 # easting of AOI's left edge, if prj_dem exists, this param value will be ignored
    #ymin: 6430000 # northing of AOI's bottom edge, if prj_dem exists, this param value will be ignored
    #xmax: 1125000 # easting of AOI's right edge, if prj_dem exists, this param value will be ignored
    #ymax: 7962000 # northing of AOI's top edge, if prj_dem exists, this param value will be ignored

    ### TEMPORAL RANGE ###
    months: 01 02 03 04 05 06 07 08 09 10 11 12
    first_year: 1998
    last_year: 2001
########################################################################################################################



### PROJECT NAME ###
gtopo30norway1km:

    ### DEFINE PATHS TO IMPORTANT DIRECTORIES ###
    src_dem: /home/sl_wib/ITopo/data/gtopo30arcsec_norway.tif
    srb_dir: /space/wib_data/CLIMATE/NASA/srb_monthly_utc/
    itopo_dir: /home/sl_wib/ITopo/gtopo30norway1km/

    ### DEFINE SPATIAL EXTENTS ###
    # If epsg does not match src_dem, gdalwarp might reproject src_dem to produce aoi dem
    # If EPSG is not given, it is derived from src_dem.
    #epsg:   32633 # EPSG code for AOI projection. if prj_dem exists, this param value will be ignored
    #dx:      1000 # E-W Resolution of prj_dem and output. if prj_dem exists, this param value will be ignored
    #dy:     -1000 # (negative) N-S Resolution of prj_dem and output. if prj_dem exists, this param value will be ignored
    #min:  -85000 # easting of AOI's left edge, if prj_dem exists, this param value will be ignored
    #ymin: 6430000 # northing of AOI's bottom edge, if prj_dem exists, this param value will be ignored
    #xmax: 1125000 # easting of AOI's right edge, if prj_dem exists, this param value will be ignored
    #ymax: 7962000 # northing of AOI's top edge, if prj_dem exists, this param value will be ignored

    ### TEMPORAL RANGE ###
    months: 01 02 03 04 05 06 07 08 09 10 11 12
    first_year: 1998
    last_year: 2001
########################################################################################################################